services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./usr/local/bin:/mnt/usr/local/bin
      - ./project:/home/project
    tty: true
    working_dir: /home
    command: /bin/bash
