#ifndef _TYPES_H
#define _TYPES_H

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef unsigned long long u64;

typedef signed char s8;
typedef signed short s16;
typedef signed int s32;
typedef signed long long s64;

typedef int BOOL;
typedef u8 S_BOOL;

#define NULL ((void *)0)
#define TRUE (1)
#define FALSE (0)

typedef u16 STRCODE;
typedef u16 PMS_WORD;
typedef struct {
  u16 size;
  u16 strlen;
  u32 magicNumber;

  STRCODE buffer[1];
} STRBUF;

typedef struct {
  u32 offset;
  u32 len;
} MSG_PARAM_BLOCK;

typedef struct {
  u32 numMsgs;
  u32 randValue;
  MSG_PARAM_BLOCK params[];
} MSGDATA_HEADER;

typedef void ARCHANDLE;

typedef struct {
  u16 type;
  u16 heapId;
  u16 archiveId;
  u16 dataId;

  union {
    MSGDATA_HEADER *msgData;
    ARCHANDLE *arcHandle;
  };
} MSGDATA_MANAGER;

typedef struct {
  u32 x;
  u32 y;
  u32 z;
} VecFx32;

typedef void POKEMON_PASO_PARAM;

typedef struct {
  u8 def_article;
  u8 indef_article;
  u8 preposition;
  u8 grammer : 7;
  u8 form : 1;
} WORDSET_PARAM;

typedef struct {
  WORDSET_PARAM param;
  STRBUF *str;
} WORD;

typedef struct {
  u32 max;
  u32 heapID;
  WORD *word;
  STRBUF *tmpBuf;
} WORDSET;

enum { TYPE_NORMAL = 0, TYPE_ARCHIVE, TYPE_CUSTOM_POKE_NICKNAME };

typedef struct {
  u16 type;
  u16 exists;
  u16 dataId;
  u16 strId;
  u16 size;
  u16 offset;
} CUSTOM_MSG_HEADER;

static const CUSTOM_MSG_HEADER *customMsgHeaders =
    (CUSTOM_MSG_HEADER *)0x023C8000;

enum {
  ARC_WAZA_SEQ = 0,
  ARC_SUB_SEQ,
  ARC_PERSONAL,
  ARC_GROW_TBL,
  ARC_POKE_GRA,
  ARC_POKE_HEIGHT,
  ARC_TRB_GRA,
  ARC_BATT_BG,
  ARC_BATT_OBJ,
  ARC_BATT_BG_PLANM,
  ARC_WAZA_EFF,
  ARC_WAZA_TBL,
  ARC_SCRIPT,
  ARC_SCRIPT_MSG,
  ARC_POKETCH_IMG,
  ARC_BAG_GRA,
  ARC_FONT,
  ARC_ITEMDATA,
  ARC_ITEMICON,
  ARC_BOX2_GRA,
  ARC_POKEICON,
  ARC_PLIST_GRA,
  ARC_WER_CHAR,
  ARC_WER_PLTT,
  ARC_WER_CELL,
  ARC_WER_CELLANM,
  ARC_IMAGECLIP_GRA,
  ARC_MSG,
  ARC_UG_RADAR_GRA,
  ARC_WAZA_PARTICLE,
  ARC_BE_SEQ,
  ARC_NAMEIN_GRA,
  ARC_EVENTDATA,
  ARC_WOTBL,
  ARC_EVO,
  ARC_FONTOAM,
  ARC_FIELD_BOARD,
  ARC_D_ENCOUNT,
  ARC_WINFRAME,
  ARC_PSTATUS_GRA,
  ARC_FLD_3D_STRUCT,
  ARC_MAP_MATRIX,
  ARC_AREA_DATA,
  ARC_AREA_BUILD_MODEL,
  ARC_AREA_TEX_SET,
  ARC_UGEFFECT_GRA,
  ARC_TITLE,
  ARC_MMDL,
  ARC_UG_TRAP_GRA,
  ARC_TR_CASE_GRA,
  ARC_UG_FOSSIL_GRA,
  ARC_NTAG_GRA,
  ARC_TRADELIST_GRA,
  ARC_UG_PARTS_GRA,
  ARC_OPENING_GRA,
  ARC_TRDATA,
  ARC_TRPOKE,
  ARC_TRTBL,
  ARC_TRF_GRA,
  ARC_PARTICLE_DATA,
  ARC_SHOP_GRA,
  ARC_WAZA_EFF_SUB,
  ARC_UG_ANIM_GRA,
  ARC_WEATHER_SYS_GRA,
  ARC_MENU_GRA,
  ARC_FIELD_MAP_DATA,
  ARC_NUTSDATA,
  ARC_ZUKAN_GRA,
  ARC_ZUKAN2_GRA,
  ARC_POKEFOOT_GRA,
  ARC_BM_TEX_SET,
  ARC_BPLIST_GRA,
  ARC_CONFIG_GRA,
  ARC_UNIONROOM_GRA,
  ARC_ZUKAN_DATA,
  ARC_PMSI_GRAPHIC,
  ARC_BBAG_GRA,
  ARC_OEKAKI_GRA,
  ARC_MAIL_GRA,
  ARC_FNOTE_GRA,
  ARC_MMODEL,
  ARC_FIRST_POKE_SELECT,
  ARC_FLDCOMACT_GRA,
  ARC_RECORD_GRA,
  ARC_WIFINOTE_GRA,
  ARC_CONTEST_DATA,
  ARC_CUSTOM_BALL_GRA,
  ARC_WIFIP2PMATCH_GRA,
  ARC_DEMO_TRADE_GRA,
  ARC_POKE_ANM,
  ARC_MYSIGN_GRA,
  ARC_MMODEL_LIST,
  ARC_FIELD_CUTIN_GRA,
  ARC_FIELD_DEMO_CLI_GRA,
  ARC_BALL_PARTICLE,
  ARC_SAMPLE_PARTICLE,
  ARC_DENDOU_PC_GRA,
  ARC_WIFI_EARCH_PLACE,
  ARC_TR_AI,
  ARC_WORLDTRADE_GRA,
  ARC_DENDOU_DEMO,
  ARC_ENCDATA_EX,
  ARC_FLDEFF,
  ARC_VS_DEMO_GRA,
  ARC_POKE_ZUKAN,
  ARC_BM_ANM,
  ARC_BM_INFO_OUT_LIST,
  ARC_BM_INFO_IN_LIST,
  ARC_ENCOUNTEFFECT,
  ARC_WAZAOSHIE_GRA,
  ARC_POKE_ANM_TBL,
  ARC_FIELD_TRADE_POKE,
  ARC_MYSTERY_GRA,
  ARC_OTHER_POKE,
  ARC_EGGDEMO_GRA,
  ARC_EGGDEMO_PARTICLE,
  ARC_SHIP_DEMO,
  ARC_OTHER_HEIGHT,
  ARC_BTOWER_APP,
  ARC_SHINKA_DEMO,
  ARC_INTRO,
  ARC_TV,
  ARC_ENDING,
  ARC_OP_DEMO,
  ARC_WIFI_EARTH,
  ARC_RANKING_GRA,
  ARC_PPARK_DATA,
  ARC_SYOUJYOU,
  ARC_SLOT,
  ARC_BTD_TR,
  ARC_BTD_PM,
  ARC_INTRO_TV,
  ARC_TRTBL_OFS,
  ARC_POKE_YOFS,
  ARC_ZUKAN_ENC_DIAMOND,
  ARC_ZUKAN_ENC_PEARL,
  ARC_HIDEN_EFFECT,
  ARC_POKE_SHADOW,
  ARC_P_ENCOUNT,
  ARC_POKE_SHADOW_OFX,
  ARC_POKE_ZUKAN_GS,
  ARC_FIELD_TRANS_ANIME,
  ARC_GROUND_ANM,
  ARC_PAIR_POKE_INFO,
  ARC_PGEAR_GRA,
  ARC_PGSYS_GRA,
  ARC_PGMAP_GRA,
  ARC_PGSKIN_GRA,
  ARC_PGTEL_GRA,
  ARC_PGRADIO_GRA,
  ARC_ROOM_3D_STRUCT,
  ARC_POKETHLON_POKE,
  ARC_DUNGEONCUT_GRA,
  ARC_POKESEL_GRA,
  ARC_YNTOUCH_GRA,
  ARC_PKTHLN,
  ARC_PKTHEV_DAT,
  ARC_PKTHEV_OPED,
  ARC_PKTHEV_LOGO,
  ARC_PKTHEV_DASH,
  ARC_PKTHEV_BOUND,
  ARC_PKTHEV_NUTS,
  ARC_PKTHEV_BOMB,
  ARC_PKTHEV_RESULT,
  ARC_PKTHEV_BOARD,
  ARC_POKESTATUS_GRA,
  ARC_AREA_WIN_GRA,
  ARC_EV_POKESELECT_GRA,
  ARC_SBOX_GRA,
  ARC_SAFARIL_GRA,
  ARC_PKTHEV_PUSH,
  ARC_PKTHEV_JUMP,
  ARC_PKTHPOKE_PARAM,
  ARC_PKTHEVT_PARAM,
  ARC_ALBUM_GRA,
  ARC_AN_PUZZLE_GRA,
  ARC_FLD_DEMO_GRA,
  ARC_CLACT_HEADER,
  ARC_MICTEST_GRP,
  ARC_PKTH_MUSEUM_GRA,
  ARC_PKTHEV_RUN,
  ARC_WIFI2DCHAR,
  ARC_PM_EDIT,
  ARC_TEST_FILE,
  ARC_FRONTIER_SCRIPT,
  ARC_FRONTIER_BG,
  ARC_FRONTIER_OBJ,
  ARC_CB_EDIT,
  ARC_WIFIUNIONCHAR,
  ARC_GURU2,
  ARC_FRONTIER_PARTICLE,
  ARC_BUCKET_GRAPHIC,
  ARC_CODE_GRA,
  ARC_BR_GRA,
  ARC_WORLDTIMER,
  ARC_BALANCE_BALL_GRA,
  ARC_DP_POKE_GRA,
  ARC_DP_OTHER_POKE,
  ARC_DP_POKE_HEIGHT,
  ARC_DP_OTHER_HEIGHT,
  ARC_LOBBY_NEWS,
  ARC_EMAIL_GRA,
  ARC_WLMNGM_TOOL_GRA,
  ARC_BALLOON_GRA,
  ARC_WFLBY_MAP,
  ARC_WFLBY_GRA,
  ARC_PL_BTD_TR,
  ARC_PL_BTD_PM,
  ARC_PL_STAGE_PM,
  ARC_SCRATCH,
  ARC_POKELIST_PARTICLE,
  ARC_WIFILOBBY_OTHER_GRA,
  ARC_FOOTPRINT_GRA,
  ARC_ZUKAN_ENC_PLATINUM,
  ARC_BUCKET_DATA,
  ARC_PL_ETC_PARTICLE,
  ARC_PMS_AIKOTOBA_DATA,
  ARC_2DUNIONOBJ_FRONT,
  ARC_ZUKAN_DATA_GIRA,
  ARC_GURU2_2D_GRA,
  ARC_NUT_PLANTER_GRA,
  ARC_PKTHEV_THROW,
  ARC_BONG_CASE_GRA,
};

#define MAX_MSGS 100

#endif // _TYPES_H
